# Generated by Django 3.2.7 on 2021-09-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.ingredients'),
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
