# Generated by Django 3.2.7 on 2021-09-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipes_shop',
        ),
    ]
